'use client'

import SimPeopleWithSuspense from "@/components/commonPeople/SimPeople"
import { useUser } from "@clerk/nextjs"
import { useEffect, useState } from "react"
import { ObjectId } from 'mongodb';
import Downbar from "@/components/Downbar/Downbar";

export interface EventPost {
  _id?: ObjectId; // Optional, generated by MongoDB
  title: string;
  caption?: string;
  image: string;
  likes?: number; // Default value is 0
  location: string;
  date: Date;
  time: string;
  createdBy: ObjectId;
  createdAt?: Date; // Managed by mongoose timestamps
  updatedAt?: Date; // Managed by mongoose timestamps
}




const BeCommunity = () => {

  const [eventPosts,setEventPosts]=useState<EventPost[]>([]);

  const {user,isLoaded}=useUser();
  useEffect(() => {
    if(!isLoaded || typeof window === "undefined"){
      return;
    }
    const fetchPosts=async()=>{
      const res=await fetch("/api/eventpost");
      const data:[]=await res.json();
      console.log("data",data)
      setEventPosts(data);
      
    }
    fetchPosts();
    
  }, [isLoaded]);

  console.log("eventposts",eventPosts)
  return (
    <div className="w-[100vw] h-auto relative">
           <div className="absolute left-[5%] right-[75%] top-5  h-[60vh]  bg-[#484444] rounded-2xl">
            <h1>Upcoming Events</h1>
            <div className="w-[90%] flex flex-col justify-center items-start ">
                {eventPosts.map((eventPost:EventPost)=>(
                  <></>
                ))}
            </div>
           </div>

            <div className="absolute left-[28%] right-[28%] top-5 h-[100vh]  bg-[#484444] rounded-2xl">
              <h1>Community Posts</h1> 
              </div>

              <div className="absolute left-[75%] right-[5%] overflow-y-scroll top-5 h-[70vh] bg-[#484444] rounded-2xl">
            <SimPeopleWithSuspense/>

              </div>
              <Downbar/>
    </div>
  )
}

export default BeCommunity